version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    container_name: api
    build:
      context: ./api-backend 
    restart: always
    volumes:
      - ./api-backend:/usr/src/app
    depends_on:
      - db
      # - redis
    networks:
      - app-network

  ntf:
    container_name: nft
    build:
      context: ./nft-backend
    # working_dir value has to be the same of mapped volume
    working_dir: /nft-backend
    ports:
      - "4000:4000"
    environment:
      - WEB3_NETWORK=testnet
      - WEB3_PRIVATE_KEY=6448415dd4c3bf6ebbb42cee99da603395434f6b459c285e0d9864c30f3bb17e
    volumes:
      - ./nft-backend/:/nft-backend/
      # - /var/run/docker.sock:/var/run/docker.soc
    networks:
      - app-network

  # redis: 
  #   container_name: redis
  #   build:
  #     context: ./infra/redis
  #   networks:
  #     - app-network

  frontend:
    container_name: frontend
    build:
      context: ./front-end
    volumes:
      - ./front-end:/usr/src/app
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    image: nginx:1.21.6-alpine
    restart: on-failure
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge